#!/bin/bash

usr_packages=""

while getopts "p:cm" opts; do
    case ${opts} in
    p|package)
    # learned how to store contents of a file in a var from
    # https://stackoverflow.com/questions/14116748/need-to-assign-the-contents-of-a-text-file-to-a-variable-in-a-bash-script
    export usr_packages=$(<${OPTARG})
    # learned how to export variables so its availible in inner scripts from
    # https://stackoverflow.com/questions/56277967/passing-variables-inside-a-variable-to-nested-script

    # Learned how to run a file within another script from
    # https://stackoverflow.com/questions/8352851/how-to-call-one-shell-script-from-another-shell-script
    source ./pkge_installer

    ;;
    c|configure)

    source ./linker

    ;;
    m|man)
    cat << EOF
    Usage: 

    setup [options] <packages>

    Description:

    This script will help you install a suite of packages and/or pre-configure the package

    Options:

    -p, -package </path/to/file>

    This option will take in a file with package names and install them all for the user

    -c, -configure

    This option will create symbolic links between the cloned files and create links from the pre configured files

EOF
    ;;

    *)
    ;;
    esac
done









